
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author reinaldo
 */
public class EditarFuncionario extends javax.swing.JDialog {
    
    private static MainGerente mainGerente;
    private static Funcionario func;

    private DefaultComboBoxModel<String> grBoxModel = new DefaultComboBoxModel<String>();
    private static List<Gerente> gerentes;
    private static int index;
    
    
    public EditarFuncionario(Funcionario f, List<Gerente> gerentes, int index, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.mainGerente = (MainGerente)parent;
        this.gerentes = gerentes;
        this.func = f;
        this.index = index;
        for(Gerente g : gerentes)
            grBoxModel.addElement(g.getNome());
        
        initComponents();
        
        userFuncField.setText(func.getUsuario());
        senhaFuncField.setText(func.getSenha());
        rgFuncField.setText(func.getDocumento());
        nascFuncField.setText(func.getNasc().string());
        admFuncField.setText(func.getAdmissao().string());
        salarioFuncField.setText(Double.toString(func.getSalario()).replaceAll(".", ","));
        nomeFuncField.setText(func.getNome());
        
        if(func instanceof VendedorJr)
            anosFuncField.setText(((VendedorJr)func).getTempoTrabalho() + "");
        if(func instanceof VendedorS)
            anosFuncField.setText(((VendedorS)func).getAnosTrabalho() + "");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeFuncField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userFuncField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        senhaFuncField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rgFuncField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        salarioFuncField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        nascFuncField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        admFuncField = new javax.swing.JFormattedTextField();
        posFuncField = new javax.swing.JComboBox<>();
        grFuncField = new javax.swing.JComboBox<>();
        tempoLabel = new javax.swing.JLabel();
        anosFuncField = new javax.swing.JTextField();
        criarFuncButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Senha:");

        jLabel4.setText("RG:");

        jLabel5.setText("Salario:");

        salarioFuncField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel6.setText("Data de nascimento:");

        nascFuncField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel7.setText("Data de admissão:");

        admFuncField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        posFuncField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor Jr", "Vendedor Sr", "Gerente" }));
        posFuncField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posFuncFieldActionPerformed(evt);
            }
        });

        grFuncField.setModel(grBoxModel);

        tempoLabel.setText("Anos de trabalho:");

        criarFuncButton.setText("Pronto");
        criarFuncButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarFuncButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(criarFuncButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeFuncField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rgFuncField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(senhaFuncField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioFuncField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nascFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(admFuncField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posFuncField, 0, 107, Short.MAX_VALUE)
                            .addComponent(grFuncField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tempoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anosFuncField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(senhaFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rgFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(salarioFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nascFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(admFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempoLabel)
                    .addComponent(anosFuncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criarFuncButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posFuncFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posFuncFieldActionPerformed
        // TODO add your handling code here:
        int index  = posFuncField.getSelectedIndex();
        switch(index){
            case 0:
                anosFuncField.setEnabled(true);
                tempoLabel.setText("Tempo de trabalho:");
                grFuncField.setEnabled(true);
                break;
            case 1:
                anosFuncField.setEnabled(true);
                tempoLabel.setText("Anos de trabalho:");
                grFuncField.setEnabled(false);
                break;
            case 2:
                anosFuncField.setEnabled(false);
                grFuncField.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_posFuncFieldActionPerformed

    private void criarFuncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarFuncButtonActionPerformed
        // TODO add your handling code here:
        if(!userFuncField.getText().equals(func.getUsuario()))
            func.setUsuario(userFuncField.getText());
        if(!senhaFuncField.getText().equals(func.getSenha()))
            func.setSenha(senhaFuncField.getText());
        if(!rgFuncField.getText().equals(func.getDocumento()))
            func.setDocumento(rgFuncField.getText());
        if(!nascFuncField.getText().equals(func.getNasc().string()))
            func.setNasc(new Data(nascFuncField.getText()));
        if(!admFuncField.getText().equals(func.getAdmissao().string()))
            func.setAdmissao(new Data(admFuncField.getText()));
        if(!salarioFuncField.getText().equals(Double.toString(func.getSalario()).replaceAll(".", ",")))
            func.setSalario(Double.parseDouble(salarioFuncField.getText().replaceAll(",", ".")));
        if(!nomeFuncField.getText().equals(func.getNome()))
            func.setNome(nomeFuncField.getText());
        int option = posFuncField.getSelectedIndex();
        Funcionario funcionario;
        switch(option){
            case 0:
                VendedorJr junior = (VendedorJr)func;
                if(!anosFuncField.getText().equals(junior.getTempoTrabalho() + ""))
                    junior.setTempoTrabalho(Integer.parseInt(anosFuncField.getText()));
                mainGerente.editFuncionario(junior, this.index);
                break;
            case 1:
                VendedorS senior = (VendedorS)func;
                if(!anosFuncField.getText().equals(senior.getAnosTrabalho()+ ""))
                    senior.setAnosTrabalho(Integer.parseInt(anosFuncField.getText()));
                mainGerente.editFuncionario(senior, this.index);
                break;
            default:
                Gerente gerente = (Gerente)func;
                mainGerente.editFuncionario(gerente, this.index);                                
                break;
        }
        this.show(false);
    }//GEN-LAST:event_criarFuncButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovoFuncionario dialog = new NovoFuncionario(gerentes, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField admFuncField;
    private javax.swing.JTextField anosFuncField;
    private javax.swing.JButton criarFuncButton;
    private javax.swing.JComboBox<String> grFuncField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField nascFuncField;
    private javax.swing.JTextField nomeFuncField;
    private javax.swing.JComboBox<String> posFuncField;
    private javax.swing.JTextField rgFuncField;
    private javax.swing.JFormattedTextField salarioFuncField;
    private javax.swing.JTextField senhaFuncField;
    private javax.swing.JLabel tempoLabel;
    private javax.swing.JTextField userFuncField;
    // End of variables declaration//GEN-END:variables
}
