

public class EditarMoto extends javax.swing.JDialog {
    
    private MainGerente mainGerente = null;
    private MainVendedor mainVendedor = null;
    private Motocicleta moto;
    private int index;

    /**
     * Creates new form NovoCliente
     */
    public EditarMoto(Motocicleta m, int index, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        if(parent instanceof MainGerente)
            this.mainGerente = (MainGerente)parent;        
        if(parent instanceof MainVendedor)
            this.mainVendedor = (MainVendedor)parent;
        
        this.moto = m;
        this.index = index;
        this.setTitle(moto.getMarca() + ", " + moto.getModelo());
        
        initComponents();
        
        
        chassiField.setText(moto.getChassi() + "");
        marcaMotoField.setText(moto.getMarca());
        modeloMotoField.setText(moto.getModelo());
        anoField.setText(moto.getAno() + "");
        kmField.setText(moto.getKm() + "");
        combField.setText(moto.getComb());
        pesoField.setText(moto.getPeso() + "");
        statusMotoBox.setSelectedIndex(getStatusIndex(moto.getStatus()));
        cilindradasField.setText(moto.getCilindradas() + "");
        tipoMotoBox.setSelectedIndex(getTipoIndex(moto.getTipo()));
    }
    
    private int getTipoIndex(Motocicleta.Tipo t){
        if(t == Motocicleta.Tipo.TRAIL)
            return 0;
        else if(t == Motocicleta.Tipo.STREET)
            return 1;
        else if(t == Motocicleta.Tipo.ESPORTIVA)
            return 2;
        else
            return 3;
    }
    
    private int getStatusIndex(Veiculo.Status s){
        if(s == Veiculo.Status.A_VENDA)
            return 0;
        else
            return 1;
    }
    
    private Motocicleta.Tipo getTipo(int index){
        switch(index){
            case 0:
                return Motocicleta.Tipo.TRAIL;
            case 1:
                return Motocicleta.Tipo.STREET;
            case 2:
                return Motocicleta.Tipo.ESPORTIVA;
            default:
                return Motocicleta.Tipo.CUSTOM;
        }
    }
    
    private Veiculo.Status getStatus(int index){
        switch(index){
            case 0:
                return Veiculo.Status.A_VENDA;
            default:
                return Veiculo.Status.VENDIDO;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        modeloMotoField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cilindradasField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        anoField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pesoField = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        criarButton = new javax.swing.JButton();
        chassiField = new javax.swing.JFormattedTextField();
        marcaMotoField = new javax.swing.JTextField();
        combField = new javax.swing.JTextField();
        kmField = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tipoMotoBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        statusMotoBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Modelo:");

        modeloMotoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloMotoFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca:");

        cilindradasField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cilindradasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cilindradasFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Cilindradas:");

        jLabel4.setText("Chassi:");

        anoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel5.setText("Ano:");

        jLabel6.setText("Combustivel:");

        jLabel7.setText("Peso:");

        pesoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        jLabel8.setText("Kilometragem:");

        criarButton.setText("Pronto");
        criarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarButtonActionPerformed(evt);
            }
        });

        chassiField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        combField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combFieldActionPerformed(evt);
            }
        });

        kmField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        jLabel9.setText("Tipo:");

        tipoMotoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trail", "Street", "Esportiva", "Custom" }));

        jLabel10.setText("Status:");

        statusMotoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A venda", "Vendida" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(criarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modeloMotoField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chassiField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anoField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesoField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kmField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcaMotoField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cilindradasField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoMotoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusMotoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(modeloMotoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(marcaMotoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(anoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(chassiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pesoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(kmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cilindradasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tipoMotoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(statusMotoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeloMotoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloMotoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloMotoFieldActionPerformed

    private void criarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarButtonActionPerformed
        // TODO add your handling code here:
        //Verificar se tudo foi preenchido
        if(!modeloMotoField.getText().equals(moto.getModelo()))
            moto.setModelo(modeloMotoField.getText());
        if(!cilindradasField.getText().equals(Integer.toString(moto.getCilindradas())))
            moto.setCilindradas(Integer.parseInt(cilindradasField.getText()));
        if(!chassiField.getText().equals(Integer.toString(moto.getChassi())))
            moto.setChassi(Integer.parseInt(chassiField.getText()));
        if(!anoField.getText().equals(Integer.toString(moto.getAno())))
            moto.setAno(Integer.parseInt(anoField.getText()));
        if(!combField.getText().equals(moto.getComb()))
            moto.setComb(combField.getText());
        if(!pesoField.getText().equals(Double.toString(moto.getPeso()).replaceAll(".", ",")))
            moto.setPeso(Double.parseDouble(pesoField.getText().replaceAll(",", ".")));
        if(!kmField.getText().equals(Double.toString(moto.getKm()).replaceAll(".", ",")))
            moto.setKm(Double.parseDouble(kmField.getText().replaceAll(",", ".")));
        if(getStatus(statusMotoBox.getSelectedIndex()) != moto.getStatus())
            moto.setStatus(getStatus(statusMotoBox.getSelectedIndex()));
        if(getTipo(tipoMotoBox.getSelectedIndex()) != moto.getTipo())
            moto.setTipo(getTipo(tipoMotoBox.getSelectedIndex()));
            
        if(mainGerente != null)mainGerente.editMoto(moto, index);
        if(mainVendedor != null)mainVendedor.editMoto(moto, index);
        
        this.setVisible(false);
    }//GEN-LAST:event_criarButtonActionPerformed

    private void cilindradasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cilindradasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cilindradasFieldActionPerformed

    private void combFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovoCliente dialog = new NovoCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField anoField;
    private javax.swing.JFormattedTextField chassiField;
    private javax.swing.JFormattedTextField cilindradasField;
    private javax.swing.JTextField combField;
    private javax.swing.JButton criarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField kmField;
    private javax.swing.JTextField marcaMotoField;
    private javax.swing.JTextField modeloMotoField;
    private javax.swing.JFormattedTextField pesoField;
    private javax.swing.JComboBox<String> statusMotoBox;
    private javax.swing.JComboBox<String> tipoMotoBox;
    // End of variables declaration//GEN-END:variables
}
