
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class MainGerente extends javax.swing.JFrame {
    
    private static List<Funcionario> funcionarios;
    
    private static List<Gerente> gerentes;
    private static List<VendedorS> vendedoresSenior;
    private static List<VendedorJr> vendedoresJunior;
    private static List<Cliente> clientes;
    private static List<Carro> carros;
    private static List<Motocicleta> motos;
    private static List<VendaPrazo> vendasPrazo;
    private static Funcionario user;
    private static DefaultListModel<String> clientesListModel = new DefaultListModel<String>();
    private static DefaultListModel<String> motosListModel = new DefaultListModel<String>();
    private static DefaultListModel<String> carrosListModel = new DefaultListModel<String>();
    private static DefaultListModel<String> vendasListModel = new DefaultListModel<String>();
    
    private static int selectedClientIndex;
    private static int selectedMotoIndex;
    private static int selectedCarroIndex;
    private static int selectedVendaIndex;
    
    private static FilesIO log = new FilesIO(Dados.LOG_PATH);
    
    
    private static Date date = new Date();
    private static DateFormat horasDateFormat = new SimpleDateFormat("HH:mm:ss");

    /**
     * Creates new form Main
     */
    public MainGerente(List<Funcionario> f) {
        
        this.setTitle("Gerente");
        this.funcionarios = f;
        
        //Load files
        FilesIO<Cliente> clienteLoader = new FilesIO(Dados.CLIENTES_PATH);
        clientes = clienteLoader.read();
        FilesIO<Carro> carroLoader = new FilesIO(Dados.CARROS_PATH);
        carros = carroLoader.read();
        FilesIO<Motocicleta> motoLoader = new FilesIO(Dados.MOTOS_PATH);
        motos = motoLoader.read();
        FilesIO<VendaPrazo> vendasLoader = new FilesIO(Dados.VENDAS_PATH);
        vendasPrazo = vendasLoader.read(); 
        
        for(VendaPrazo v : vendasPrazo)
            v.atualizar(clientes, f);
        
        initComponents();
        
        if(clientes.isEmpty()){
            deletarClienteButton.setEnabled(false);
            editarClienteButton.setEnabled(false);
            mudarClienteAtual(-1);
        }else{
            mudarClienteAtual(0);            
        }
        
        if(motos.isEmpty()){
            deletarMotosButton.setEnabled(false);
            editarMotosButton.setEnabled(false);
            mudarMotoAtual(-1);
        }else{
            mudarMotoAtual(0);
        }
        
        if(carros.isEmpty()){
            deletarCarroButton.setEnabled(false);
            editarCarrosButton.setEnabled(false);
            mudarCarroAtual(-1);
        }else{
            mudarCarroAtual(0);
        }
        
        if(vendasPrazo.isEmpty()){
            deletarVenda.setEnabled(false);
            editarVenda.setEnabled(false);
            mudarVendaAtual(-1);
        }else{
            mudarVendaAtual(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        editarVenda = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        clienteVendaLabel = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        veiculoVendaLabel = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        valorVendaLabel = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        descontoVendaLabel = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        dataVendaLabel = new javax.swing.JLabel();
        vendedorVendaLabel = new javax.swing.JLabel();
        tipoVendaLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        deletarVenda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        editarCarrosButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        modeloCarroLabel = new javax.swing.JLabel();
        marcaCarroLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        anoCarroLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        chassiCarroLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pesoCarroLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        combCarroLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        kmCarroLabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        potenciaCarroLabel = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cilindrosCarroLabel = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        ocupantesCarroLabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tipoCarroLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        alturaCarroLabel = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        statusCarroLabel = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        larguraCarroLabel = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        comprimentoCarroLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        carrosList = new javax.swing.JList<>();
        salvarCarrosButton = new javax.swing.JButton();
        novoCarroButton = new javax.swing.JButton();
        deletarCarroButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        motosList = new javax.swing.JList<>();
        salvarMotosButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        editarMotosButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        modeloMotoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        marcaMotoLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chassiMotoLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        anoMotoLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pesoMotoLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        combMotoLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kmMotoLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cilindradasLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tipoMotoLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        statusMotoLabel = new javax.swing.JLabel();
        novoMotosButton = new javax.swing.JButton();
        deletarMotosButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesList = new javax.swing.JList<>();
        novoClienteButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rgLabel = new javax.swing.JLabel();
        nascLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editarClienteButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rendaLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ruaLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dpLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        salvarButton = new javax.swing.JButton();
        deletarClienteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editarVenda.setText("Editar");

        jLabel34.setText("Vendedor:");

        jLabel36.setText("Cliente:");

        jLabel38.setText("Veiculo:");

        jLabel41.setText("Tipo:");

        jLabel42.setText("Valor:");

        jLabel44.setText("Desconto:");

        jLabel46.setText("Data:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendedorVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteVendaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veiculoVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descontoVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataVendaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(vendedorVendaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(clienteVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(veiculoVendaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel40)
                        .addComponent(jLabel41)
                        .addComponent(tipoVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel42)
                        .addComponent(valorVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(descontoVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel46)
                        .addComponent(dataVendaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addComponent(editarVenda))
        );

        for(VendaPrazo v : vendasPrazo)
        vendasListModel.addElement(v.getVeiculo().getModelo() + " para " + v.getCliente().getNome());
        jList1.setModel(vendasListModel);
        jScrollPane4.setViewportView(jList1);
        jList1.addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent ev){
                    //Algo
                    int index = jList1.getSelectedIndex();
                    if(index >= 0 && index < carros.size()){
                        selectedVendaIndex = index;
                        mudarVendaAtual(index);
                    }else{
                        selectedVendaIndex = -1;
                        mudarVendaAtual(-1);
                    }
                }
            }

        );

        jButton1.setText("Nova venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        deletarVenda.setText("Apagar");
        deletarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(deletarVenda)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tab.addTab("Vendas", jPanel1);

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editarCarrosButton.setText("Editar");
        editarCarrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCarrosButtonActionPerformed(evt);
            }
        });

        jLabel19.setText("Modelo:");

        jLabel22.setText("Marca:");

        jLabel20.setText("Chassi:");

        jLabel21.setText("Ano");

        jLabel23.setText("Peso:");

        jLabel24.setText("Combustivel:");

        jLabel25.setText("Kilometragem:");

        jLabel26.setText("Potencia:");

        jLabel27.setText("Cilindros:");

        jLabel28.setText("Ocupantes:");

        jLabel29.setText("Tipo:");

        jLabel30.setText("Status:");

        jLabel31.setText("Altura:");

        jLabel32.setText("Largura:");

        jLabel33.setText("Comprimento:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarCarrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modeloCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marcaCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chassiCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combCarroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anoCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesoCarroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kmCarroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoCarroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(potenciaCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cilindrosCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocupantesCarroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(statusCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alturaCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(larguraCarroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comprimentoCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(modeloCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(anoCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(chassiCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(pesoCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(combCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(kmCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(potenciaCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(cilindrosCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(ocupantesCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(tipoCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(statusCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(alturaCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(larguraCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(comprimentoCarroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarCarrosButton))
        );

        for(Carro c : carros)
        carrosListModel.addElement(c.getMarca() + ", " + c.getModelo());
        carrosList.setModel(motosListModel);
        carrosList.setModel(carrosListModel);
        jScrollPane3.setViewportView(carrosList);
        carrosList.addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent ev){
                    //Algo
                    int index = carrosList.getSelectedIndex();
                    if(index >= 0 && index < carros.size()){
                        selectedCarroIndex = index;
                        mudarCarroAtual(index);
                    }else{
                        selectedCarroIndex = -1;
                        mudarCarroAtual(-1);
                    }
                }
            }

        );

        salvarCarrosButton.setText("Salvar");
        salvarCarrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCarrosButtonActionPerformed(evt);
            }
        });

        novoCarroButton.setText("Novo");
        novoCarroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCarroButtonActionPerformed(evt);
            }
        });

        deletarCarroButton.setText("Deletar");
        deletarCarroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarCarroButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(salvarCarrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(novoCarroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletarCarroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novoCarroButton)
                            .addComponent(deletarCarroButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvarCarrosButton))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tab.addTab("Carros", jPanel2);

        for(Motocicleta m : motos)
        motosListModel.addElement(m.getMarca() + ", " + m.getModelo());
        motosList.setModel(motosListModel);
        jScrollPane2.setViewportView(motosList);
        motosList.addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent ev){
                    //Algo
                    int index = motosList.getSelectedIndex();
                    if(index >= 0 && index < motos.size()){
                        selectedMotoIndex = index;
                        mudarMotoAtual(index);
                    }else{
                        selectedMotoIndex = -1;
                        mudarMotoAtual(-1);
                    }
                }
            }

        );

        salvarMotosButton.setText("Salvar");
        salvarMotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarMotosButtonActionPerformed(evt);
            }
        });

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editarMotosButton.setText("Editar");
        editarMotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMotosButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo:");

        jLabel5.setText("Marca:");

        jLabel8.setText("Chassi:");

        jLabel10.setText("Ano:");

        jLabel12.setText("Peso:");

        jLabel13.setText("Combustivel:");

        jLabel15.setText("Kilometragem:");

        jLabel16.setText("Cilindradas:");

        jLabel17.setText("Tipo:");

        jLabel18.setText("Status:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarMotosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modeloMotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combMotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chassiMotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anoMotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cilindradasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoMotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcaMotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesoMotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(kmMotoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusMotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(modeloMotoLabel))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(marcaMotoLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(chassiMotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(anoMotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(pesoMotoLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(combMotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kmMotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(cilindradasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(tipoMotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(statusMotoLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarMotosButton))
        );

        novoMotosButton.setText("Novo");
        novoMotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoMotosButtonActionPerformed(evt);
            }
        });

        deletarMotosButton.setText("Deletar");
        deletarMotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarMotosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(salvarMotosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(novoMotosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletarMotosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novoMotosButton)
                            .addComponent(deletarMotosButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvarMotosButton)))
                .addContainerGap())
        );

        tab.addTab("Motos", jPanel5);

        for(Cliente c : clientes)
        clientesListModel.addElement(c.getNome());
        clientesList.setModel(clientesListModel);
        jScrollPane1.setViewportView(clientesList);
        clientesList.addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent ev){
                    //Algo
                    int index = clientesList.getSelectedIndex();
                    if(index >= 0 && index < clientes.size()){
                        selectedClientIndex = index;
                        Cliente cliente = clientes.get(index);
                        nameLabel.setText(cliente.getNome());
                        rgLabel.setText(cliente.getDocumento());
                        nascLabel.setText(cliente.getNasc().string());
                        rendaLabel.setText(Double.toString(cliente.getRenda()));
                        dpLabel.setText(cliente.getDependentes() + "");
                        ruaLabel.setText(cliente.getEndereco().getLogradouro());
                        numeroLabel.setText(cliente.getEndereco().getNumero() + "");
                        cidadeLabel.setText(cliente.getEndereco().getCidade());
                    }
                }
            }
        );

        novoClienteButton.setText("Novo");
        novoClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoClienteButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nome:");

        nameLabel.setText("nome");

        jLabel3.setText("RG:");

        rgLabel.setText("0000000000");

        nascLabel.setText("00/00/0000");

        jLabel6.setText("Data de nascimento:");

        editarClienteButton.setText("Editar");
        editarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Renda:");

        rendaLabel.setText("000.00");

        jLabel9.setText("Logradouro:");

        ruaLabel.setText("Rua Cristovão Colombo");

        jLabel11.setText("Numero:");

        numeroLabel.setText("123");

        cidadeLabel.setText("São Jose do Rio Preto");

        jLabel14.setText("Cidade:");

        dpLabel.setText("0");

        jLabel4.setText("Dependentes:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarClienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nascLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ruaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidadeLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rendaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rgLabel)
                    .addComponent(nascLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rendaLabel)
                    .addComponent(dpLabel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ruaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(numeroLabel)
                    .addComponent(cidadeLabel)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarClienteButton))
        );

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        deletarClienteButton.setText("Deletar");
        deletarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salvarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(novoClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletarClienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novoClienteButton)
                            .addComponent(deletarClienteButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvarButton)))
                .addContainerGap())
        );

        tab.addTab("Clientes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        // TODO add your handling code here:
        FilesIO<Cliente> clienteLoader = new FilesIO(Dados.CLIENTES_PATH);
        clienteLoader.write(clientes);
        date = new Date();
        log.write("Clientes salvos no arquivo por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void editarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteButtonActionPerformed
        // TODO add your handling code here:
        new EditarCliente(this, true, clientes.get(selectedClientIndex), selectedClientIndex).show();
    }//GEN-LAST:event_editarClienteButtonActionPerformed

    private void deletarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarClienteButtonActionPerformed
        // TODO add your handling code here:
        int indices[] = clientesList.getSelectedIndices();
        date = new Date();
        for(int x = 0; x < indices.length; x++){
            log.write("Cliente: " + clientes.get(indices[x] - x).getNome() + ". Apagado por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
            clientes.remove(indices[x] - x);
        }
        atualizaClientesList();
    }//GEN-LAST:event_deletarClienteButtonActionPerformed

    private void novoClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoClienteButtonActionPerformed
        // TODO add your handling code here:
        //Use jDialog or this.setEnabled(false); whatever work best :V
        new NovoCliente(this, true)
                .show();
    }//GEN-LAST:event_novoClienteButtonActionPerformed

    private void novoMotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoMotosButtonActionPerformed
        // TODO add your handling code here:
        new NovaMoto(this, true)
                .show();
    }//GEN-LAST:event_novoMotosButtonActionPerformed

    private void salvarMotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarMotosButtonActionPerformed
        // TODO add your handling code here:
        FilesIO<Motocicleta> motoLoader = new FilesIO(Dados.MOTOS_PATH);
        motoLoader.write(motos);
        date = new Date();
        log.write("Motos salvas no arquivo por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
    }//GEN-LAST:event_salvarMotosButtonActionPerformed

    private void deletarMotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarMotosButtonActionPerformed
        // TODO add your handling code here:
        int indices[] = motosList.getSelectedIndices();
        date = new Date();
        for(int x = 0; x < indices.length; x++){
            log.write("Moto: " + motos.get(indices[x] - x).getMarca() + ", " + motos.get(indices[x] - x).getModelo() + ". Apagada por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
            motos.remove(indices[x] - x);
        }
        atualizaMotosList();
    }//GEN-LAST:event_deletarMotosButtonActionPerformed

    private void editarMotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMotosButtonActionPerformed
        // TODO add your handling code here:
        new EditarMoto(motos.get(selectedMotoIndex), selectedMotoIndex, this, true).show();
    }//GEN-LAST:event_editarMotosButtonActionPerformed

    private void novoCarroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoCarroButtonActionPerformed
        // TODO add your handling code here:
        new NovoCarro(this, true)
                .show();
    }//GEN-LAST:event_novoCarroButtonActionPerformed

    private void deletarCarroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarCarroButtonActionPerformed
        // TODO add your handling code here:
        int indices[] = carrosList.getSelectedIndices();
        date = new Date();
        for(int x = 0; x < indices.length; x++){
            log.write("Carro: " + carros.get(indices[x] - x).getMarca() + ", " + carros.get(indices[x] - x).getModelo() + ". Apagado por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
            carros.remove(indices[x] - x);
        }
        atualizaCarrosList();
    }//GEN-LAST:event_deletarCarroButtonActionPerformed

    private void salvarCarrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCarrosButtonActionPerformed
        // TODO add your handling code here:
        FilesIO<Carro> carroLoader = new FilesIO(Dados.CARROS_PATH);
        carroLoader.write(carros);
        date = new Date();
        log.write("Carros salvos no arquivo por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
    }//GEN-LAST:event_salvarCarrosButtonActionPerformed

    private void editarCarrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCarrosButtonActionPerformed
        // TODO add your handling code here:
        new EditarCarro(carros.get(selectedCarroIndex), selectedCarroIndex, this, true).show();
    }//GEN-LAST:event_editarCarrosButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<Veiculo> veiculos = new ArrayList<Veiculo>();
        for(Carro c : carros)
            veiculos.add(c);
        for(Motocicleta m : motos)
            veiculos.add(m);
        new NovaVenda(veiculos , clientes, user, this, true).show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deletarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarVendaActionPerformed
        // TODO add your handling code here:
        int indices[] = jList1.getSelectedIndices();
        date = new Date();
        for(int x = 0; x < indices.length; x++){
            log.write("Venda: " + vendasListModel.getElementAt(indices[x] - x) + ". Apagada por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
            vendasPrazo.remove(indices[x] - x);
        }
        atualizaVendasList();
    }//GEN-LAST:event_deletarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        //Things here don't get executed

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGerente(funcionarios).setVisible(true);
                
            }
        });
    }
    
    public void setGerentes(List<Gerente> gerentes){
        this.gerentes = gerentes;
    }
        
    public void setVendedoresS(List<VendedorS> vendedoresSenior){
        this.vendedoresSenior = vendedoresSenior;
    }
            
    public void setVendedoresJr(List<VendedorJr> vendedoresJunior){
        this.vendedoresJunior = vendedoresJunior;
    }
    
    public void setUsuario(Funcionario user){
        this.user = user;
    }
    
    public void addCliente(Cliente c){
        clientes.add(c);
        date = new Date();
        log.write("Cliente: " + c.getNome() + ". Adicionado por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
        atualizaClientesList();
    }
    
    public void addMoto(Motocicleta m){
        motos.add(m);
        date = new Date();
        log.write("Moto: " + m.getMarca() + ", " + m.getModelo() + ". Adicionada por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
        atualizaMotosList();
    }
    
    public void addCarro(Carro c){
        carros.add(c);
        date = new Date();
        log.write("Carro: " + c.getMarca() + ", " + c.getModelo() + ". Adicionado por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
        atualizaCarrosList();
    }
    
    public void addVenda(VendaPrazo v){
        vendasPrazo.add(v);
        date = new Date();
        log.write("Venda realizada por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
        atualizaVendasList();
        FilesIO<VendaPrazo> vendaLoader = new FilesIO(Dados.VENDAS_PATH);
        vendaLoader.write(vendasPrazo);
    }
    
    public void editCliente(Cliente c, int index){
        clientes.set(index, c);
        date = new Date();
        log.write("Cliente: " + c.getNome() + ". Editado por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
        atualizaClientesList();
    }
    
    public void editMoto(Motocicleta m, int index){
        motos.set(index, m);
        date = new Date();
        log.write("Moto: " + m.getMarca() + ", " + m.getModelo() + ". Editada por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
        atualizaMotosList();
    }
    
    public void editCarro(Carro c, int index){
        carros.set(index, c);
        date = new Date();
        log.write("Carro: " + c.getMarca() + ", " + c.getModelo() + ". Editado por: " + user.getNome() + ". As " + horasDateFormat.format(date) + ".");
        atualizaCarrosList();
    }
    
    private void atualizaClientesList(){
        clientesListModel.removeAllElements();
        for(Cliente cliente : clientes)
            clientesListModel.addElement(cliente.getNome());
        if(clientes.isEmpty()){
            deletarClienteButton.setEnabled(false);
            editarClienteButton.setEnabled(false);
            mudarClienteAtual(-1);
        }else{
            deletarClienteButton.setEnabled(true);
            editarClienteButton.setEnabled(true);
            mudarClienteAtual(0);            
        }
    }
    
    private void atualizaMotosList(){
        motosListModel.removeAllElements();
        for(Motocicleta moto : motos)
            motosListModel.addElement(moto.getMarca() + ", " + moto.getModelo());
        if(motos.isEmpty()){
            deletarMotosButton.setEnabled(false);
            editarMotosButton.setEnabled(false);
            mudarMotoAtual(-1);
        }else{
            deletarMotosButton.setEnabled(true);
            editarMotosButton.setEnabled(true);
            mudarMotoAtual(0);            
        }
    }
    
    private void atualizaCarrosList(){
        carrosListModel.removeAllElements();
        for(Carro carro : carros)
            carrosListModel.addElement(carro.getMarca() + ", " + carro.getModelo());
        if(carros.isEmpty()){
            deletarCarroButton.setEnabled(false);
            editarCarrosButton.setEnabled(false);
            mudarCarroAtual(-1);
        }else{
            deletarCarroButton.setEnabled(true);
            editarCarrosButton.setEnabled(true);
            mudarCarroAtual(0);
            
        }
        
    }
    
    private void atualizaVendasList(){
        vendasListModel.removeAllElements();
        for(VendaPrazo v : vendasPrazo)
            vendasListModel.addElement(v.getVeiculo().getModelo() + " para " + v.getCliente().getNome());
        if(vendasPrazo.isEmpty()){
            editarVenda.setEnabled(false);
            deletarVenda.setEnabled(false);
            mudarVendaAtual(-1);
        }else{
            editarVenda.setEnabled(true);
            deletarVenda.setEnabled(true);
            mudarVendaAtual(0);
        }
    }
    
    private void mudarVendaAtual(int index){
        if(index >= 0){
            VendaPrazo venda = vendasPrazo.get(index);
            vendedorVendaLabel.setText(venda.getVendedor().getNome());
            clienteVendaLabel.setText(venda.getCliente().getNome());
            veiculoVendaLabel.setText(venda.getVeiculo().getMarca() + ", " + venda.getVeiculo().getModelo());
            if(venda.getVeiculo() instanceof Carro)
                tipoVendaLabel.setText("Carro");
            else
                tipoVendaLabel.setText("Motocicleta");
            valorVendaLabel.setText(venda.getValor() + "");
            descontoVendaLabel.setText(venda.getDesconto() + "");
            dataVendaLabel.setText(venda.getData().string());
        }else{
            vendedorVendaLabel.setText("");
            clienteVendaLabel.setText("");
            veiculoVendaLabel.setText("");
            tipoVendaLabel.setText("");
            valorVendaLabel.setText("");
            descontoVendaLabel.setText("");
            dataVendaLabel.setText("");            
        }
    }
    
    private void mudarClienteAtual(int index){
        if(index >= 0){
            Cliente cliente = clientes.get(index);
            nameLabel.setText(cliente.getNome());
            rgLabel.setText(cliente.getDocumento());
            nascLabel.setText(cliente.getNasc().string());
            rendaLabel.setText(Double.toString(cliente.getRenda()));
            dpLabel.setText(cliente.getDependentes() + "");
            ruaLabel.setText(cliente.getEndereco().getLogradouro());
            numeroLabel.setText(cliente.getEndereco().getNumero() + "");
            cidadeLabel.setText(cliente.getEndereco().getCidade());
        }else{
            
            nameLabel.setText("");
            rgLabel.setText("");
            nascLabel.setText("");
            rendaLabel.setText("");
            dpLabel.setText("");
            ruaLabel.setText("");
            numeroLabel.setText("");
            cidadeLabel.setText("");
            
        }
    }
    
    private void mudarMotoAtual(int index){
        if(index >= 0){
            Motocicleta moto = motos.get(index);
            marcaMotoLabel.setText(moto.getMarca());
            modeloMotoLabel.setText(moto.getModelo());
            chassiMotoLabel.setText(Integer.toString(moto.getChassi()));
            anoMotoLabel.setText(moto.getAno() + "");
            pesoMotoLabel.setText(moto.getPeso() + "");
            combMotoLabel.setText(moto.getComb());
            kmMotoLabel.setText(moto.getKm() + "");
            cilindradasLabel.setText(moto.getCilindradas() + "");
            tipoMotoLabel.setText(moto.getTipo().toString().toLowerCase());
            statusMotoLabel.setText(moto.getStatus().toString().replaceAll("_", " ").toLowerCase());
        }else{
            marcaMotoLabel.setText("");
            modeloMotoLabel.setText("");
            chassiMotoLabel.setText("");
            anoMotoLabel.setText("");
            pesoMotoLabel.setText("");
            combMotoLabel.setText("");
            kmMotoLabel.setText("");
            cilindradasLabel.setText("");
            tipoMotoLabel.setText("");
            statusMotoLabel.setText("");            
        }
    }
    
    private void mudarCarroAtual(int index){
        if(index >= 0){
            Carro carro = carros.get(index);
            chassiCarroLabel.setText(carro.getChassi() + "");
            marcaCarroLabel.setText(carro.getMarca());
            modeloCarroLabel.setText(carro.getModelo());
            anoCarroLabel.setText(carro.getAno() + "");
            kmCarroLabel.setText(carro.getKm() + "");
            combCarroLabel.setText(carro.getComb());
            pesoCarroLabel.setText(carro.getPeso() + "");
            statusCarroLabel.setText(carro.getStatus().toString().replaceAll("_", " ").toLowerCase());
            potenciaCarroLabel.setText(carro.getPotencia() + "");
            cilindrosCarroLabel.setText(carro.getCilindros() + "");
            ocupantesCarroLabel.setText(carro.getOcupantes() + "");
            tipoCarroLabel.setText(carro.getTipo().toString().toLowerCase());
            alturaCarroLabel.setText(carro.getDimensoes().getAltura() + "");
            larguraCarroLabel.setText(carro.getDimensoes().getLargura() + "");
            comprimentoCarroLabel.setText(carro.getDimensoes().getComprimento() + "");
        }else{
            chassiCarroLabel.setText("");
            marcaCarroLabel.setText("");
            modeloCarroLabel.setText("");
            anoCarroLabel.setText("");
            kmCarroLabel.setText("");
            combCarroLabel.setText("");
            pesoCarroLabel.setText("");
            statusCarroLabel.setText("");
            potenciaCarroLabel.setText("");
            cilindrosCarroLabel.setText("");
            ocupantesCarroLabel.setText("");
            tipoCarroLabel.setText("");
            alturaCarroLabel.setText("");
            larguraCarroLabel.setText("");
            comprimentoCarroLabel.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alturaCarroLabel;
    private javax.swing.JLabel anoCarroLabel;
    private javax.swing.JLabel anoMotoLabel;
    private javax.swing.JList<String> carrosList;
    private javax.swing.JLabel chassiCarroLabel;
    private javax.swing.JLabel chassiMotoLabel;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JLabel cilindradasLabel;
    private javax.swing.JLabel cilindrosCarroLabel;
    private javax.swing.JLabel clienteVendaLabel;
    private javax.swing.JList<String> clientesList;
    private javax.swing.JLabel combCarroLabel;
    private javax.swing.JLabel combMotoLabel;
    private javax.swing.JLabel comprimentoCarroLabel;
    private javax.swing.JLabel dataVendaLabel;
    private javax.swing.JButton deletarCarroButton;
    private javax.swing.JButton deletarClienteButton;
    private javax.swing.JButton deletarMotosButton;
    private javax.swing.JButton deletarVenda;
    private javax.swing.JLabel descontoVendaLabel;
    private javax.swing.JLabel dpLabel;
    private javax.swing.JButton editarCarrosButton;
    private javax.swing.JButton editarClienteButton;
    private javax.swing.JButton editarMotosButton;
    private javax.swing.JButton editarVenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel kmCarroLabel;
    private javax.swing.JLabel kmMotoLabel;
    private javax.swing.JLabel larguraCarroLabel;
    private javax.swing.JLabel marcaCarroLabel;
    private javax.swing.JLabel marcaMotoLabel;
    private javax.swing.JLabel modeloCarroLabel;
    private javax.swing.JLabel modeloMotoLabel;
    private javax.swing.JList<String> motosList;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nascLabel;
    private javax.swing.JButton novoCarroButton;
    private javax.swing.JButton novoClienteButton;
    private javax.swing.JButton novoMotosButton;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JLabel ocupantesCarroLabel;
    private javax.swing.JLabel pesoCarroLabel;
    private javax.swing.JLabel pesoMotoLabel;
    private javax.swing.JLabel potenciaCarroLabel;
    private javax.swing.JLabel rendaLabel;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JLabel ruaLabel;
    private javax.swing.JButton salvarButton;
    private javax.swing.JButton salvarCarrosButton;
    private javax.swing.JButton salvarMotosButton;
    private javax.swing.JLabel statusCarroLabel;
    private javax.swing.JLabel statusMotoLabel;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JLabel tipoCarroLabel;
    private javax.swing.JLabel tipoMotoLabel;
    private javax.swing.JLabel tipoVendaLabel;
    private javax.swing.JLabel valorVendaLabel;
    private javax.swing.JLabel veiculoVendaLabel;
    private javax.swing.JLabel vendedorVendaLabel;
    // End of variables declaration//GEN-END:variables
}
