;http://www.onlinepiccompiler.com/compiler16f84av1ENG.php
;Setar entradas e saidas
BANKSEL TRISA
CLRF TRISB
BANKSEL PORTA

CENTENA  EQU 0X1F
DEZENA   EQU 0X1E
UNIDADE  EQU 0X1D
NUMERO   EQU 0X1C
AUX      EQU 0X1B
RES      EQU 0X1A

;Programa principal
MAIN
CALL ENTRADA ; Ler dados das portas
CALL PRINTERO
CALL ACHAPRIMO
CALL SAIDA ; Converter o numero em NUMERO pra BCD 
MOVF CENTENA, 0
CALL PRINTERO
MOVF DEZENA, 0
CALL PRINTERO
MOVF UNIDADE, 0
CALL PRINTERO

PRINTERO
MOVWF PORTB
BTFSS PORTA, 4
GOTO PRINTERO
DESAPERTA
BTFSC PORTA, 4
GOTO DESAPERTA
RETURN

ENTRADA
MOVLW 0X00 ; Zera o contador de numeros entrados
MOVWF AUX

ESPERA ; Espera entrada de um novo numero
BTFSS PORTA, 4
GOTO ESPERA
INCF AUX, 1 ; Incrementa o contador de numeros entrados

MOVF AUX, 0 ; Testa se aux = 1
SUBLW 1
BTFSC STATUS, 2
GOTO CENT ; Se sim estamos lendo as centenas
MOVF AUX, 0 ; Se nau testa se aux = 2
SUBLW 2
BTFSC STATUS, 2
GOTO DEZ ; Se sim estamos lendo as dezenas
GOTO UNI ; Se nau soh pode ser as unidades

CENT
MOVF PORTA, 0 ; Lê entrada na porta e salva no registrador W
MOVWF CENTENA
BCF CENTENA, 4
ABAIXARBOTAO
BTFSC PORTA, 4
GOTO ABAIXARBOTAO
GOTO ESPERA

DEZ
MOVF PORTA, 0 ; Lê entrada na porta e salva no registrador W
MOVWF DEZENA
BCF DEZENA, 4
ABAIXARBOTAO2
BTFSC PORTA, 4
GOTO ABAIXARBOTAO2
GOTO ESPERA

UNI
MOVF PORTA, 0 ; Lê entrada na porta e salva no registrador W
MOVWF UNIDADE
BCF UNIDADE, 4

MOVLW 0                   ; Converte a centena
MOVWF NUMERO
MOVWF RES
MOVLW 0X19
MOVWF AUX
RLF CENTENA, 1
RLF CENTENA, 0
CALL MULTIPLY
MOVF RES, 0
ADDWF NUMERO, 1
MOVLW 0                   ; Converte a dezena
MOVWF RES
MOVLW 5
MOVWF AUX
RLF DEZENA, 0
CALL MULTIPLY
MOVF RES, 0
ADDWF NUMERO, 1
MOVF UNIDADE, 0     ; Converte a unidade
ADDWF NUMERO, 1

MOVF NUMERO, 0
RETURN

SAIDA
MOVLW 0
MOVWF CENTENA
MOVWF DEZENA
MOVWF UNIDADE
MOVF NUMERO, 0
MOVWF AUX

CENTSAIDA
MOVLW 64
SUBWF AUX, 1
INCF CENTENA, 1
SUBWF AUX, 0
BTFSC STATUS, 2
GOTO FIMSAIDA
BTFSC STATUS, 0
GOTO CENTSAIDA

DEZSAIDA
MOVLW 0A
SUBWF AUX, 1
INCF DEZENA, 1
SUBWF AUX, 0
BTFSC STATUS, 2
GOTO FIMSAIDA
BTFSC STATUS, 0
GOTO DEZSAIDA

MOVF AUX, 0
MOVWF UNIDADE

FIMSAIDA
RETURN

MULTIPLY
ADDWF RES, 1
DECFSZ AUX, 1
GOTO MULTIPLY
RETURN

ACHAPRIMO